name: stock_pulse
description: "A new stock market android application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_typeahead: ^4.0.0
  syncfusion_flutter_charts:
  shared_preferences: ^2.0.11
  url_launcher: ^6.1.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  convex_bottom_bar:

flutter_icons:
  android: true
  image_path: "assets/images/logo_unnamed.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
